### ISSUE TITLE
Using this addon from within my script

### ISSUE THREAD

**Issue by AdvancedStyle** [JuhaW/NodeArrange#10]
Hello I'm working on script which imports some shader nodes.

It would be nice to be able to use NodeArrange from within my script, so after creating a new material and some shader node, it is as if the user has click the "Arrange All Nodes" button.

Is there an easy way to do with in Python (assuming the user does **NOT** have the NodeArrange addon enabled)?

So basically a script to automatically enable the addon and automatically click the button at certain times.

**Comment by JuhaW** [comment]
To enable Node Arrange: 
bpy.ops.preferences.addon_enable(module = "node_arrange")

And executing "Arrange all nodes":
bpy.ops.node.button()

If your script button(s) are on Shader Editor panel then you dont need to override context.

**Comment by AdvancedStyle** [comment]
Thanks for your help.  Your addon now gets automatically enabled :+1: 

However i'm having errors when calling `bpy.ops.node.button()`

My Button is in the Shader Editor sidebar but it has it's own Panel (not in the "Arrang" panel)

```
Error: Python: Traceback (most recent call last):
  File "/home/david/.config/blender/2.92/scripts/addons/shadercloud.py", line 281, in invoke
    result = self.execute(context)
  File "/home/david/.config/blender/2.92/scripts/addons/shadercloud.py", line 269, in execute
    bpy.ops.node.button()
  File "/home/david/Applications/blender-2.92.0-linux64/2.92/scripts/modules/bpy/ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/david/Applications/blender-2.92.0-linux64/2.92/scripts/addons/node_arrange.py", line 179, in execute
    nodemargin(self, context)
  File "/home/david/Applications/blender-2.92.0-linux64/2.92/scripts/addons/node_arrange.py", line 224, in nodemargin
    ntree = context.space_data.node_tree
AttributeError: 'NoneType' object has no attribute 'node_tree'
```

**Comment by JuhaW** [comment]
```
import bpy

for area in bpy.context.screen.areas:
    if area.type == 'NODE_EDITOR':
        for region in area.regions:
            if region.type == 'WINDOW':
                ctx = bpy.context.copy()
                ctx['area'] = area
                ctx['region'] = region
                bpy.ops.node.button(ctx, "INVOKE_DEFAULT")

```

**Comment by Shadercloud** [comment]
Thanks working now 👍

**Comment by MehdiZangenehBar** [comment]
This dosn't work:

```
import bpy

bpy.ops.preferences.addon_enable(module = "node_arrange")


for area in bpy.context.screen.areas:
    if area.type == 'NODE_EDITOR':
        for region in area.regions:
            if region.type == 'WINDOW':
                ctx = bpy.context.copy()
                ctx['area'] = area
                ctx['region'] = region
                bpy.ops.node.button(ctx, "INVOKE_DEFAULT")
```

**Comment by MehdiZangenehBar** [comment]
Is it possible to call the function like for example Arrange(node_tree) and pass my own node_tree?
